# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-23 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(default='14:30', verbose_name='Horario Inicio')),
                ('horario_fim', models.TimeField(default='14:30', verbose_name='Horario Fim')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
