# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0009_auto_20170721_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrita', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_fim',
            field=models.TimeField(default='20:05', verbose_name='Horario Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_inicio',
            field=models.TimeField(default='20:05', verbose_name='Horario Inicio'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
