# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-21 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0010_auto_20170721_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='recursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('nome_google', models.CharField(max_length=50, verbose_name='nome_google')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254)),
                ('tipo', models.IntegerField(choices=[(0, 'Sala'), (1, 'Aparelho')], verbose_name='tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_fim',
            field=models.TimeField(default='20:52', verbose_name='Horario Fim'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='horario_inicio',
            field=models.TimeField(default='20:52', verbose_name='Horario Inicio'),
        ),
    ]
